<?php

namespace app\models;
use GuzzleHttp\Psr7\UploadedFile;
use yii\behaviors\AttributeBehavior;
use yii\db\ActiveRecord;

use Yii;

/**
 * This is the model class for table "book".
 *
 * @property integer $id
 * @property string $title
 * @property string $image
 * @property string $author
 * @property string $date
 * @property string $date_add
 */
class Book extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'book';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'author'], 'required'],
            [['date'], 'safe'],
            [['date_add'], 'default', 'value' => date('d.m.Y')],
            [['title', 'author'], 'string', 'max' => 255],
        ];
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'image' => 'Image',
            'author' => 'Author',
            'date' => 'Date',
            'date_add' => 'Date Add',
        ];
    }

    public function getAll(){

        $data = self::find()
            ->all();

        return $data;
    }

    public function saveImage($filename){

        $this->image = $filename;

         $saved = $this->save(false);

         return $saved;
    }

    public function getImage(){
        return ($this->image) ? '/uploads/' . $this->image : '/no-image.png';
    }


    public function deleteImage(){
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}
